# Generated by Django 4.0.5 on 2022-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('project_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
