# Generated by Django 4.0.5 on 2022-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='user_project', to='awwards.review'),
        ),
    ]
