# Generated by Django 4.0.5 on 2022-06-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_projectdata_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.PositiveSmallIntegerField(choices=[(1, '1- Very Dissatisfied'), (2, '2- Dissatisfied'), (3, '3- bad'), (4, '4- OK'), (5, '5- neutral'), (6, '6- good'), (7, '7- very good'), (8, '8- Extremly good'), (9, '9- Perfect'), (10, '10 - Master Piece')], default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='usability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1- Very Dissatisfied'), (2, '2- Dissatisfied'), (3, '3- bad'), (4, '4- OK'), (5, '5- neutral'), (6, '6- good'), (7, '7- very good'), (8, '8- Extremly good'), (9, '9- Perfect'), (10, '10 - Master Piece')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.PositiveSmallIntegerField(choices=[(1, '1- Very Dissatisfied'), (2, '2- Dissatisfied'), (3, '3- bad'), (4, '4- OK'), (5, '5- neutral'), (6, '6- good'), (7, '7- very good'), (8, '8- Extremly good'), (9, '9- Perfect'), (10, '10 - Master Piece')], default=0),
        ),
    ]
