# Generated by Django 4.0.5 on 2022-06-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_projectdata_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdata',
            name='posted_by',
        ),
    ]
