# Generated by Django 4.0.5 on 2022-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to='awwards.review'),
        ),
    ]
